name: med-scale-nk
channels:
  - conda-forge
  - plotly

  - nodefaults

dependencies:
  - python=3.11
  - pip >=21.1
  - setuptools_scm
  - toml

  # Reproducibility
  - conda-lock

  # Package dependencies
  - pytask>=0.2
  - pytask-latex>=0.2

  # Misc
  - black
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-xdist
  - tox-conda

  - pdbpp
  - ipykernel
  - jupyterlab
  - pyyaml
  - plotly>=5.5.0
  - pandas
  - numpy
  - statsmodels
  - python-graphviz
  - python-kaleido


  - pip:
    - econpizza
    - -e .  # installs the project
